//Create a new file, which will become the currently active document
//Write a header in the new active document
//Click on "Scripting" --> "Scripts" --> "Add"
//UltraEdit.newFile();
var myDate=new Date();
myDate.setDate(myDate.getDate());
var copyrightyear = (myDate.getFullYear());

var dashes = "; ------------------------------------------------------------";
dashes += "----------------\r\n";
UltraEdit.activeDocument.top();
UltraEdit.activeDocument.write(dashes);
UltraEdit.activeDocument.write("ssh -f username@servername -L:6868:127.0.0.1:22 -N \r\n");
UltraEdit.activeDocument.write("ssh username@servername \"ls -al *.txt\" \r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("Send email with message: \r\n");
UltraEdit.activeDocument.write("mail -s \"This is the subject\" someone@example.com \r\n");
UltraEdit.activeDocument.write("Hi someone \r\n");
UltraEdit.activeDocument.write("How are you \r\n");
UltraEdit.activeDocument.write("I am fine \r\n");
UltraEdit.activeDocument.write("Bye \r\n");
UltraEdit.activeDocument.write("EOT \r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("Send email and include content from a file:\r\n");
UltraEdit.activeDocument.write("mail -s \"This is Subject\" someone@example.com < /path/to/file\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("Send email and by echoing the content and piping to mail:\r\n");
UltraEdit.activeDocument.write("echo \"This is message body\" | mail -s \"This is Subject\" someone@example.com\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("Multiple recipients:\r\n");
UltraEdit.activeDocument.write("echo \"This is message body\" | mail -s \"This is Subject\" someone@example.com,someone2@example.com\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("CC and BCC:\r\n");
UltraEdit.activeDocument.write("echo \"This is message body\" | mail -s \"This is Subject\" -b ccuser@example.com someone@example.com\r\n");
UltraEdit.activeDocument.write("echo \"This is message body\" | mail -s \"This is Subject\" -c ccuser@example.com someone@example.com\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("Specify a FROM address use the \"-r\" option. The name should be followed by the address wrapped in \"<>\".:\r\n");
UltraEdit.activeDocument.write("echo \"This is message body\" | mail -s \"This is Subject\" -r \"Billybob<billybob@example.com>\" someone@example.com\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("Specify reply to address: \r\n");
UltraEdit.activeDocument.write("The reply to address is set with the internal option variable \"replyto\" using the \"-S\" option. \r\n");
UltraEdit.activeDocument.write("# replyto email\r\n");
UltraEdit.activeDocument.write("$ echo \"This is message\" | mail -s \"Testing replyto\" -S replyto=\"mark@gmail.com\" someone@example.com\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("# replyto email with a name\r\n");
UltraEdit.activeDocument.write("$ echo \"This is message\" | mail -s \"Testing replyto\" -S replyto=\"Mark<mark@gmail.com>\" someone@example.com\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("Add attachments:\r\n");
UltraEdit.activeDocument.write("echo \"This is message body\" | mail -s \"This is Subject\" -r \"Harry<harry@gmail.com>\" -a /path/to/file someone@example.com\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("Source for email lines - https://www.binarytides.com/linux-mailx-command/ \r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write("\r\n");
UltraEdit.activeDocument.write(dashes + " \r\n");